//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LechTyper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LechTyper.Resources.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mnie.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywacja konta.
        /// </summary>
        public static string AccountActivation {
            get {
                return ResourceManager.GetString("AccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do ukończenia rejestracji wymagane jest kliknięcie w link zawarty w wiadomości email wysłanej do Ciebie.
        /// </summary>
        public static string AccountActivationMessage {
            get {
                return ResourceManager.GetString("AccountActivationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiązane konta.
        /// </summary>
        public static string AccountAssociate {
            get {
                return ResourceManager.GetString("AccountAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń powiązanie z kontem.
        /// </summary>
        public static string AccountAssociateDeleteWith {
            get {
                return ResourceManager.GetString("AccountAssociateDeleteWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz konto lokalne!.
        /// </summary>
        public static string AccountLocalCreate {
            get {
                return ResourceManager.GetString("AccountLocalCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odzyskaj konto.
        /// </summary>
        public static string AccountRetrive {
            get {
                return ResourceManager.GetString("AccountRetrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd aktywacji!.
        /// </summary>
        public static string ActivationError {
            get {
                return ResourceManager.GetString("ActivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W Twojej wiadomości był błąd. Proszę spróbować jeszcze raz lub skontatkować się z administratorem..
        /// </summary>
        public static string ActivationErrorMessage {
            get {
                return ResourceManager.GetString("ActivationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel administracyjny.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co planujesz zepsuć?.
        /// </summary>
        public static string AdminWelcome {
            get {
                return ResourceManager.GetString("AdminWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga Mistrzów.
        /// </summary>
        public static string ChampionsLeague {
            get {
                return ResourceManager.GetString("ChampionsLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzony.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzony terminarz.
        /// </summary>
        public static string CreateFixture {
            get {
                return ResourceManager.GetString("CreateFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstraklasa.
        /// </summary>
        public static string Ekstraklasa {
            get {
                return ResourceManager.GetString("Ekstraklasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga Europy.
        /// </summary>
        public static string EuropaLeague {
            get {
                return ResourceManager.GetString("EuropaLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieudane logowanie przy pomocy serwisu społecznościowego..
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminarz.
        /// </summary>
        public static string Fixture {
            get {
                return ResourceManager.GetString("Fixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stracone.
        /// </summary>
        public static string GoalConceded {
            get {
                return ResourceManager.GetString("GoalConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strzelone.
        /// </summary>
        public static string GoalScored {
            get {
                return ResourceManager.GetString("GoalScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do góry.
        /// </summary>
        public static string GoTop {
            get {
                return ResourceManager.GetString("GoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cześć.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga.
        /// </summary>
        public static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awanse i spadki.
        /// </summary>
        public static string LeaguePromotions {
            get {
                return ResourceManager.GetString("LeaguePromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizacja składów lig.
        /// </summary>
        public static string LeagueUserUpdate {
            get {
                return ResourceManager.GetString("LeagueUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd logowania!.
        /// </summary>
        public static string LogFailure {
            get {
                return ResourceManager.GetString("LogFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona Główna.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozgrywki.
        /// </summary>
        public static string MatchCompetition {
            get {
                return ResourceManager.GetString("MatchCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolejka.
        /// </summary>
        public static string MatchDay {
            get {
                return ResourceManager.GetString("MatchDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja meczu.
        /// </summary>
        public static string MatchEdit {
            get {
                return ResourceManager.GetString("MatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytujesz mecz.
        /// </summary>
        public static string MatchEditing {
            get {
                return ResourceManager.GetString("MatchEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mecze.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gość.
        /// </summary>
        public static string MatchGuest {
            get {
                return ResourceManager.GetString("MatchGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik do przerwy.
        /// </summary>
        public static string MatchHalf {
            get {
                return ResourceManager.GetString("MatchHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gospodarz.
        /// </summary>
        public static string MatchHome {
            get {
                return ResourceManager.GetString("MatchHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie meczami.
        /// </summary>
        public static string MatchManage {
            get {
                return ResourceManager.GetString("MatchManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozegrany?.
        /// </summary>
        public static string MatchPlayed {
            get {
                return ResourceManager.GetString("MatchPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        public static string MatchResult {
            get {
                return ResourceManager.GetString("MatchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdobywca bramki.
        /// </summary>
        public static string MatchScorer {
            get {
                return ResourceManager.GetString("MatchScorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs.
        /// </summary>
        public static string MatchVs {
            get {
                return ResourceManager.GetString("MatchVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string PasswordForgot {
            get {
                return ResourceManager.GetString("PasswordForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetowanie hasła.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw hasło.
        /// </summary>
        public static string PasswordSet {
            get {
                return ResourceManager.GetString("PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz jeszcze ustawionego hasła. Dodaj je aby nie korzystać z zewnętrznego serwisu do logowania..
        /// </summary>
        public static string PaswordMessage {
            get {
                return ResourceManager.GetString("PaswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typer.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puchar Polski.
        /// </summary>
        public static string PolishCup {
            get {
                return ResourceManager.GetString("PolishCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superpuchar Polski.
        /// </summary>
        public static string PolishSupercup {
            get {
                return ResourceManager.GetString("PolishSupercup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycja.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja wpisu.
        /// </summary>
        public static string PostEdit {
            get {
                return ResourceManager.GetString("PostEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytujesz wpis.
        /// </summary>
        public static string PostEditing {
            get {
                return ResourceManager.GetString("PostEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id postu.
        /// </summary>
        public static string PostId {
            get {
                return ResourceManager.GetString("PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Prediction {
            get {
                return ResourceManager.GetString("Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja typu.
        /// </summary>
        public static string PredictionEdit {
            get {
                return ResourceManager.GetString("PredictionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj typami.
        /// </summary>
        public static string PredictionManage {
            get {
                return ResourceManager.GetString("PredictionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typy.
        /// </summary>
        public static string Predicts {
            get {
                return ResourceManager.GetString("Predicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się jeśli jeszcze nie masz konta..
        /// </summary>
        public static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się przy pomocy Twojego konta społecznościowego.
        /// </summary>
        public static string RegisterSocial {
            get {
                return ResourceManager.GetString("RegisterSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udało Ci się ukończyć proces rejestracji. Teraz możesz się zalogować!.
        /// </summary>
        public static string RegistrationMessage {
            get {
                return ResourceManager.GetString("RegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja zakończona!.
        /// </summary>
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętać?.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie rolami użytkowników.
        /// </summary>
        public static string RoleAddToUser {
            get {
                return ResourceManager.GetString("RoleAddToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypisz rolę użytkownikowi.
        /// </summary>
        public static string RoleAddUser {
            get {
                return ResourceManager.GetString("RoleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowe role.
        /// </summary>
        public static string RoleCreate {
            get {
                return ResourceManager.GetString("RoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie roli.
        /// </summary>
        public static string RoleCreating {
            get {
                return ResourceManager.GetString("RoleCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz role użytkownika.
        /// </summary>
        public static string RoleGet {
            get {
                return ResourceManager.GetString("RoleGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa roli.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie rolami.
        /// </summary>
        public static string RolesManage {
            get {
                return ResourceManager.GetString("RolesManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role użytkownika.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś pewny by usunąć?.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #LechTyper.
        /// </summary>
        public static string Tittle {
            get {
                return ResourceManager.GetString("Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpis.
        /// </summary>
        public static string TwitterPost {
            get {
                return ResourceManager.GetString("TwitterPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizacje.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie kontem.
        /// </summary>
        public static string UserAccountManage {
            get {
                return ResourceManager.GetString("UserAccountManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś zalogowany jako.
        /// </summary>
        public static string UserCurrentlyLoged {
            get {
                return ResourceManager.GetString("UserCurrentlyLoged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja użytkownika.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytujesz.
        /// </summary>
        public static string UserEditing {
            get {
                return ResourceManager.GetString("UserEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id użytkownika.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj użytkownikami.
        /// </summary>
        public static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wpisz Twoją nazwę użytkownika poniżej i kliknij &quot;Zaloguj&quot; by zakończyć proces rejestracji..
        /// </summary>
        public static string VerificationMessage {
            get {
                return ResourceManager.GetString("VerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udało Ci się zweryfikować konto!.
        /// </summary>
        public static string VerificationSuccess {
            get {
                return ResourceManager.GetString("VerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
